project:
  type: book
  output-dir: docs

book:
  title: "PATOQ"
  author: "<a href='https://arashabadi.github.io/'>Arash B. Abadi</a>"
  date: last-modified
  cover-image: images/patoq_cover_t.png
  repo-url: https://github.com/arashabadi/patoq
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - part: prerequisites.qmd
      chapters: 
        - biology_fundamentals.qmd
        - mathematics_fundamentals.qmd
        - computer_science_fundamentals.qmd
    - part: "Special topics"
      chapters:
        - omics-data.qmd
        - modeling-simulation.qmd
        - integrated-platforms.qmd
        - specialized-topics.qmd
    - part: "Additional Resources"
      chapters:
        - additional-resources.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: true
    code-fold: true
    code-tools: true
    repo-url: https://github.com/arashabadi/patoq
    edit-url: https://github.com/arashabadi/patoq/edit/main/
    toc: true
    toc-expand: true
    link-external-icon: true
    link-external-newwindow: true
    navbar:
      right:
        - icon: github
          href: https://github.com/arashabadi/patoq
        - icon: edit
          href: https://github.com/arashabadi/patoq/edit/main/
